version : '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: dev_db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_phpmyadmin
    links:
      - db:db
    environment:
      PMA_HOST: 192.168.0.8
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8181:80
